In [227]:
# ベクトル作成関数
function x_vector(xₙ, M)
    xₙₘ = zeros(length(xₙ), M)
    for m in 1:M
        xₙₘ[:,m] = xₙ.^(m-1)
    end
    xₙₘ
end

# 確認
#x_vector(1:5, 4)

# 真の次元数
M_truth = 4
W_truth = rand(-1:0.1:1,4)

# 
#X_line = range(-3, 3, length=200)



x_vector (generic function with 1 method)

In [228]:
x_vector(1:5, 4)

5×4 Array{Float64,2}:
 1.0  1.0   1.0    1.0
 1.0  2.0   4.0    8.0
 1.0  3.0   9.0   27.0
 1.0  4.0  16.0   64.0
 1.0  5.0  25.0  125.0

In [222]:
a = 1:5

1:5

In [224]:
a.^3

5-element Array{Int64,1}:
   1
   8
  27
  64
 125

In [219]:
X[:,2]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [127]:
N = 5
X = [
    1 1 1 1
    1 2 4 8
    1 3 9 27
    1 4 16 64
]

W = rand(-1:0.1:1,4)

Yₜ = X*W

#using Plots
#plot(X[:,2], Y)

using Distributions
λ = 0.4
ϵ = rand(Normal(0,√inv(λ)),　N)


5-element Array{Float64,1}:
 -0.7160972417715565
 -2.1708205629880046
  3.404138051296579
 -1.4512053085875245
 -0.17239618398595777

In [123]:
ϵ

5-element Array{Float64,1}:
  0.20007028236073432
 -1.2279520800188344
  2.356180572436881
  4.0999661042650954
  0.17132949529221345

In [115]:
W

4-element Array{Float64,1}:
 -1.0
 -0.7
  0.1
  0.8